- cmd/main.go
- pkg/service/blobs/options.go
- pkg/service/blobs/server.go
- pkg/service/blobs/service.go
- pkg/service/claims/options.go
- pkg/service/claims/server.go
- pkg/service/claims/service.go
- pkg/service/publisher/publisher.go
- pkg/service/publisher/publisher_test.go
- pkg/service/storage/options.go
- pkg/service/storage/service.go
- pkg/service/storage/ucan.go
This PR allows configuration of the indexing service DID/URL and upgrades `publisher.Publish(...)` to make a `claim/cache` invocation to it.
TODO: actually send the claim in the invocation blocks (needs ucanto upgrade). See: https://github.com/storacha/go-ucanto/pull/27
> feat: cache location claim in indexing service

- go.sum
- pkg/server/server.go
- pkg/service/publisher/server.go
This PR fixes the server paths - only return version info when direct hit on `/` and fix for IPNI advert path - includes a CID.
> fix(publisher): server paths

- pkg/server/server.go
- pkg/service/storage/ucan.go
- pkg/service/storage/ucan_test.go
This PR fixes the response for a repeated `blob/allocate` for an existing blob.
Previously:
* Not allocated and not received - allocated size: {blob size} and signed URL for put
* Not allocated and received (allocated in another space) - allocated size: {blob size} and signed URL for put
* Allocated but not received - allocated size: {blob size} and signed URL for put
* Allocated and received - allocated size: 0, no URL
Now:
* Not allocated and not received - allocated size: {blob size} and signed URL for put
* Not allocated and received (allocated in another space) - allocated size: {blob size}, no URL
* Allocated but not received - allocated size: 0 (already allocated in the space) and signed URL for put
* Allocated and received - allocated size: 0, no URL
> fix: blob/allocate response for already allocated or received blob

- go.mod
- go.sum
- pkg/service/storage/ucan_test.go
> feat: integrate updated blob/accept capability

- go.mod
- go.sum
Upgrade `go-ucanto` to the latest version to get the fix for the server not validating invocation audiences (https://github.com/storacha/go-ucanto/pull/38).
> chore: upgrade go-ucanto to v0.3.0

- cmd/delegation.go
- cmd/flags.go
- cmd/proofset.go
- cmd/start.go
a follow on to https://github.com/storacha/storage/pull/46 that moves rest of commands to --key-file pattern.
> refactor: migrate remaining cli commands to use key-file

- deploy/pdp/README.md
- deploy/pdp/cloud-init.yaml.tpl
- deploy/pdp/configs/curio-pdp.toml
- deploy/pdp/configs/curio-storage.toml
- deploy/pdp/main.tf
- deploy/pdp/output.tf
- deploy/pdp/provider.tf
- deploy/pdp/scripts/curio-poststart.sh
- deploy/pdp/scripts/install-curio.sh
- deploy/pdp/scripts/install-go.sh
- deploy/pdp/scripts/install-lotus.sh
- deploy/pdp/scripts/install-rust.sh
- deploy/pdp/scripts/install-yugabyte.sh
- deploy/pdp/scripts/lotus-import-snapshot.sh
- deploy/pdp/scripts/lotus-import-wallets.sh
- deploy/pdp/scripts/service-ready.sh
- deploy/pdp/services/README.md
- deploy/pdp/services/curio-poststart.service
- deploy/pdp/services/curio-prestart.service
- deploy/pdp/services/curio-ready.service
- deploy/pdp/services/curio.service
- deploy/pdp/services/lotus-poststart.service
- deploy/pdp/services/lotus-prestart.service
- deploy/pdp/services/lotus-ready.service
- deploy/pdp/services/lotus.service
- deploy/pdp/services/yugabyte-ready.service
- deploy/pdp/services/yugabyte.service
- deploy/pdp/template.tf
- deploy/pdp/variables.tf
- deploy/pdp/vpc.tf
See top level [`README.md`](https://github.com/storacha/storage/blob/0ff93a070c66136365f920b62b9500ba775789d8/deploy/pdp/README.md) and [`services/README.md`](https://github.com/storacha/storage/blob/0ff93a070c66136365f920b62b9500ba775789d8/deploy/pdp/services/README.md) for details.
Addresses https://github.com/storacha/project-tracking/issues/334
> infra: implementation of Curio+Lotus deployment for PDP

- pkg/service/storage/blob_accept.go
- pkg/service/storage/blob_allocate.go
- pkg/service/storage/ucan.go
- Moves blob allocation and acceptance logic out of ucan.go to blob_allocate.go and blob_accept.go
- Separates UCAN validation, receipts, and effects from blob-specific operations
- Facilitates reuse of UCAN methods for the replication protocol
- In https://github.com/storacha/storage/pull/57 I ended up needing to refactor things here further, but this lays the ground work for the change.
> refactor: separate blob allocation and acceptance logic into dedicated files

- .github/workflows/release-binaries.yml
requires write on contents permission to fix this error: https://github.com/storacha/storage/actions/runs/14766300763/job/41458325127
> fix(ci): release-binaries workflow permissions

- cmd/enum/keyfmt.go
- cmd/identity.go
- cmd/identity_test.go
This commit enhances the identity command module with several improvements:
- Add detailed documentation to all commands with usage examples
- Improve function and variable naming for better clarity
- Implement comprehensive round-trip testing (JSON → PEM → JSON and PEM → JSON → PEM)
- Add an example application demonstrating proper usage of the identity tools
- Update error messages to be more specific and helpful
- Ensure consistent code style throughout the module
- Make all exported functions properly documented
The improved round-trip testing ensures key integrity is maintained during format conversions, which is critical for security-sensitive cryptographic operations. This commit does not change any functionality but significantly improves code quality and testability.
```bash …
```
> refactor(identity): improve code readability and add round trip testing

- pkg/pdp/testing/pdp_test.go
- until we implement a mockable clock via https://github.com/storacha/storage/issues/80
> testing: skip PDP-based testing

- .goreleaser.yaml
was previously calling it `storage`
> fix: go-releaser names binary `piri`

- pkg/aws/s3blobstore.go
- pkg/presigner/s3.go
- pkg/presigner/s3_test.go
This adds the missing checksum in presigned requests.
I had to google hard for how to do this in Go. Finally found https://github.com/aws/aws-sdk/issues/480#issuecomment-2065197264
Existing presigned URLs did not include `x-amz-checksum-sha256` in the signed headers and wasn't returning the `x-amz-checksum-sha256` as a header that the client needs to send.
AWS doesn't support `x-amz-checksum-sha256` in the query string - it is silently ignored on the backend. However, it can be a request header, and we _do_ want it to be one of the signed headers.
URL: `http://localhost:3000/data/zQmcuYW5AG3STkAqxGowojKzEfWYRssRdUEyJJAnFawLPNN?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=did%3Akey%3Az6MkrLosJPxqiQdTccuJ6csvZ5eV6RT4ZqEYhNxP7x8wGXJq%2F20250701%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20250 …
> fix: checksum in presigned requests

- pkg/principalresolver/httpresolver_test.go
- test remains in place for manual smoke tests
> fix: skip test dialing real service

- cmd/cli/serve/pdp.go
- cmd/cli/serve/ucan.go
- cmd/cliutil/util.go
- pkg/pdp/server.go
Goal: make it easier for user to understand their current server(s) configuration. Also makes sharing configuration for debugging easier.
When starting a UCAN Server, the output is now:
```bash
piri serve ucan --key-file=service.pem --pdp-server-url=http://localhost:3001 --proof-set=514
SERVER CONFIGURATION
--------------------
Host:        localhost
Port:        3000
Data Dir:    /home/frrist/.storacha
Public URL:  http://localhost:3000
Blob Addr:   /dns/localhost/tcp/3001/http/http-path/piece%2F%7BblobCID%7D
SERVICES
--------
Indexing Service:
DID:       did:web:staging.indexer.warm.storacha.network
URL:       https://staging.indexer.warm.storacha.network
Proof Set: false
Upload Service:
DID:       did:web:staging.up.warm.storacha.network
URL: …
```
> feat: print configuration details when starting servers

- cmd/cli/serve/ucan.go
when the URL is converted to a multiaddress, the trailing slash is interpreted as an alternative path (the root path). That results in an invalid multiaddress when concatenating the `claims/{claim}` path.
> fix: trim trailing slashes from public URLs

- go.mod
- go.sum
- pkg/service/publisher/publisher_test.go
- pkg/service/storage/ucan/blob_accept.go
- pkg/service/storage/ucan/blob_allocate.go
- pkg/service/storage/ucan/errors.go
- pkg/service/storage/ucan/pdp_info.go
- pkg/service/storage/ucan/replica_allocate.go
The signature for handlers changed in go-ucanto. This PR updates Piri to use the new code.
Depends on https://github.com/storacha/go-ucanto/pull/55
> chore: upgrade go-ucanto

- docs/guides/ucan-server.md
My piri version was very old and I went over the docs again. `piri serve ucan` complained that `--proof-set` is required when using `--pdp-server-url`, so I added that to the command in the docs.
> fix(docs): --proof-set is required when using --pdp-server-url

- cmd/cli/client/pdp/proofset/list.go
- cmd/cli/client/pdp/proofset/root.go
- pkg/pdp/httpapi/client/client.go
- pkg/pdp/httpapi/server/list_proofset.go
- pkg/pdp/httpapi/server/register.go
- pkg/pdp/httpapi/types.go
- pkg/pdp/service/proofset_list.go
allows users to list the proofsets their node is currently configured with. This will come in handy w/ later PRs where we init a node and a proofset automatically if one doesn't exist when a "full" node starts. The intention here is to use this API on startup in a later PR.
> feat: implement `proofset list` cli/client/api

- cmd/cli/serve/ucan.go
- pkg/fx/ucan/provider.go
Unexpected errors from handlers are sent to this function, [by default it prints to stderr](https://github.com/storacha/go-ucanto/blob/cd24d1a476ed38d5a70d443c60e0f11b361ff1f7/server/server.go#L106). This PR explicitly logs the error using our logger and prints the stack trace if the underlying cause had a stack trace.
> fix: explicitly log handler execution errors

- pkg/fx/aggregator/provider.go
- pkg/fx/replicator/provider.go
- pkg/pdp/aggregator/jobqueue/jobqueue.go
- pkg/pdp/aggregator/jobqueue/jobqueue_test.go
- pkg/pdp/aggregator/jobqueue/worker/worker.go
- pkg/pdp/aggregator/jobqueue/worker/worker_test.go
- pkg/pdp/aggregator/local.go
- pkg/service/replicator/replicate.go
- pkg/service/storage/service.go
This change does two thing:
1. Implements graceful shutdown the of the jobqueue, blocking stop calls until all active jobs complete of the stop context is cancel, while preventing new jobs from being added during shutdown
2. Implements an OnFailure option in the Job queue that is called when a job exhausts all its retries, this is useful for addressing https://github.com/storacha/piri/issues/215 - specifically the case mentioned here: https://github.com/storacha/piri/pull/216#issuecomment-3253326999
> Implement graceful shutdown of job queue w/ OnFailure method

- pkg/store/retrievaljournal/fsjournal.go
- pkg/store/retrievaljournal/fsjournal_test.go
small fix/follow-on to https://github.com/storacha/piri/pull/245
Ensures when a journal is resumed, the incremental sha is re-computed, see `TestResumeAfterRestart` for details.
> fix: incremental SHA hashing works for fsjournal resume
